import fs from 'node:fs'
const revamp = fs.readFileSync('src/revamp.ts', 'utf8')
const search = fs.readFileSync('src/optimizer/search.ts', 'utf8')
const types = fs.readFileSync('src/app-types.ts', 'utf8')
if (!revamp.includes('data-action=\"start-full\"')) throw new Error('Main optimizer action missing')
for (const removed of ['data-action=\"start-fast\"', 'Quick Search', 'Quick = faster estimate']) if (revamp.includes(removed)) throw new Error('legacy quick UI returned: '+removed)
if (!search.includes("mode: 'full'")) throw new Error('optimizer must force the thorough path')
if (!search.includes('One optimizer path') && !search.includes('one optimizer path')) throw new Error('single-mode optimizer compatibility note missing')
if (!types.includes("export type SearchMode = 'fast' | 'full'")) throw new Error('legacy SearchMode compatibility type should remain for old stored requests')
console.log('Single thorough optimizer mode regression passed.')
